### ISSUE TITLE
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by vishalkumarlondon** [FavioVazquez/twitter_optimus_twint#1]
Hey @FavioVazquez. I got the below error when I tried to run twitter_optimus_twint so I thought I'd open an issue for you to investigate!

CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:Tweets_known_error:Expecting value: line 1 column 1 (char 0)

Expecting value: line 1 column 1 (char 0) [x] run.Feed
[!] if get this error but you know for sure that more tweets exist, please open an issue and we will investigate it!

**Comment by pielco11** [comment]
Hi @vishalkumarlondon 

Sometimes Twitter plays in a strange way and might not return tweets. Do you get the error via every query? May you share your query so that I'll be able to take a look?Thanks

**Comment by fentyz** [comment]
Hi. I got same issue. I was scrapping tweet for years. I'm sure there's the tweet on each day but I dont know why sometimes there's a missing date that are not scrapped. Query still runnning while the error appear. Please help me to fix it. Here's my query
c = twint.Config()
TWITTER_QUERY = "gempa"
c.Search = TWITTER_QUERY
c.Store_csv = True
c.Output = "test.csv"
c.Lang = 'id'
c.Since = '2013-01-01'
c.Until = '2017-12-31'

**Comment by BerthaBrenes** [comment]
Same error and just following the simple code of query search and save it in a panda.
####
import twint
import pandas as pd 
c = twint.Config()
c.Search = "agroecología"
c.Pandas = True
twint.run.Search(c)
Tweets_df = twint.storage.panda.Tweets_df
Tweets_df.to_csv(r'Query2ES.csv', index = None, header=True)
twint.storage.panda.clean
####

**Comment by AldebaranNapoli** [comment]
I dont think is a problem with twitter because on my laptop works really good without errors. i did an installation, works all but not twint :(

§I can say that the first twint i used and works still now was an older versione, this is not ... 

twint -s liviovarriale --stats --count -es localhost:9200
[+] Indexing to Elasticsearch @ localhost:9200
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
....................CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:Tweets_known_error:Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0) [x] run.Feed
[!] if get this error but you know for sure that more tweets exist, please open an issue and we will investigate it!
[+] Finished: Successfully collected 1160 Tweets.






twint -s liviovarriale --stats --count -es localhost:9200
[+] Indexing to Elasticsearch @ localhost:9200
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
....................CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:Tweets_known_error:Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0) [x] run.Feed
[!] if get this error but you know for sure that more tweets exist, please open an issue and we will investigate it!
[+] Finished: Successfully collected 3400 Tweets.

twint -s ancelotti --index-tweets --since 2017-03-01 --until 2019-12-12 --stats --count -es localhost:9200
[+] Indexing to Elasticsearch @ localhost:9200
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/local/bin/twint", line 10, in <module>
    sys.exit(run_as_command())
  File "/home/wonderful/.local/lib/python3.7/site-packages/twint/cli.py", line 298, in run_as_command
    main()
  File "/home/wonderful/.local/lib/python3.7/site-packages/twint/cli.py", line 290, in main
    run.Search(c)
  File "/home/wonderful/.local/lib/python3.7/site-packages/twint/run.py", line 281, in Search
    run(config, callback)
  File "/home/wonderful/.local/lib/python3.7/site-packages/twint/run.py", line 202, in run
    get_event_loop().run_until_complete(Twint(config).main(callback))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/wonderful/.local/lib/python3.7/site-packages/twint/run.py", line 146, in main
    await task
  File "/home/wonderful/.local/lib/python3.7/site-packages/twint/run.py", line 165, in run
    await self.tweets()
  File "/home/wonderful/.local/lib/python3.7/site-packages/twint/run.py", line 137, in tweets
    await output.Tweets(tweet, self.config, self.conn)
  File "/home/wonderful/.local/lib/python3.7/site-packages/twint/output.py", line 142, in Tweets
    await checkData(tweets, config, conn)
  File "/home/wonderful/.local/lib/python3.7/site-packages/twint/output.py", line 127, in checkData
    elasticsearch.Tweet(tweet, config)
  File "/home/wonderful/.local/lib/python3.7/site-packages/twint/storage/elasticsearch.py", line 293, in Tweet
    _index_tweet_status = createIndex(config, es, scope="tweet")
  File "/home/wonderful/.local/lib/python3.7/site-packages/twint/storage/elasticsearch.py", line 121, in createIndex
    resp = instance.indices.create(index=config.Index_tweets, body=tweets_body, ignore=400)
  File "/usr/local/lib/python3.7/dist-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/elasticsearch/client/indices.py", line 102, in create
    raise ValueError("Empty value passed for a required argument 'index'.")
ValueError: Empty value passed for a required argument 'index'.
